// Copyright (c) The Bitcoin Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php.

#include <core_io.h>
#include <drivechain/m6id.h>
#include <drivechain/messages.h>
#include <primitives/transaction.h>
#include <script/script.h>
#include <test/data/drivechain_vectors.json.h>
#include <test/util/setup_common.h>
#include <uint256.h>
#include <univalue.h>
#include <util/strencodings.h>

#include <boost/test/unit_test.hpp>

#include <string>
#include <variant>
#include <vector>

using namespace drivechain;

//! Check this implementation against what the reference implementation decides.
//!
//! Every other test here says what BIP-300/301 ought to mean. These say what the
//! deployed enforcer actually does, which is the thing this port has to agree
//! with block for block. Where the two disagree one of them is wrong, and a
//! failure here names the input to look at.
//!
//! The vectors are generated by contrib/drivechain-vectors; see its README for
//! how to regenerate them and why the byte order is what it is.
namespace {
CScript ScriptFromVector(const UniValue& vector)
{
    const std::vector<unsigned char> bytes{ParseHex(vector["script"].get_str())};
    return CScript(bytes.begin(), bytes.end());
}

//! A hash written the way it appears on the wire, not the way it is displayed.
uint256 HashFromHex(const std::string& hex)
{
    const std::vector<unsigned char> bytes{ParseHex(hex)};
    BOOST_REQUIRE_EQUAL(bytes.size(), 32U);
    return uint256{bytes};
}

void CheckTreasury(const UniValue& vector)
{
    const std::optional<SlotNum> slot{ParseTreasuryScript(ScriptFromVector(vector))};
    if (vector["result"].isNull()) {
        BOOST_CHECK(!slot.has_value());
        return;
    }
    BOOST_REQUIRE(slot.has_value());
    BOOST_CHECK_EQUAL(int{*slot}, vector["result"]["slot"].getInt<int>());
}

void CheckAddress(const UniValue& vector)
{
    const auto payload{ParseOpReturnPayload(ScriptFromVector(vector))};
    if (vector["result"].isNull()) {
        BOOST_CHECK(!payload.has_value());
        return;
    }
    BOOST_REQUIRE(payload.has_value());
    BOOST_CHECK_EQUAL(HexStr(*payload), vector["result"]["payload"].get_str());
}

void CheckCoinbase(const UniValue& vector)
{
    const auto message{ParseCoinbaseMessage(ScriptFromVector(vector))};
    if (vector["result"].isNull()) {
        BOOST_CHECK(!message.has_value());
        return;
    }
    BOOST_REQUIRE(message.has_value());

    const UniValue& expected{vector["result"]};
    const std::string type{expected["type"].get_str()};
    if (type == "m1") {
        const auto* m1{std::get_if<M1ProposeSidechain>(&*message)};
        BOOST_REQUIRE(m1 != nullptr);
        BOOST_CHECK_EQUAL(int{m1->slot}, expected["slot"].getInt<int>());
        BOOST_CHECK_EQUAL(HexStr(m1->description), expected["description"].get_str());
    } else if (type == "m2") {
        const auto* m2{std::get_if<M2AckSidechain>(&*message)};
        BOOST_REQUIRE(m2 != nullptr);
        BOOST_CHECK_EQUAL(int{m2->slot}, expected["slot"].getInt<int>());
        BOOST_CHECK(m2->proposal_id == HashFromHex(expected["proposal_id"].get_str()));
    } else if (type == "m3") {
        const auto* m3{std::get_if<M3ProposeBundle>(&*message)};
        BOOST_REQUIRE(m3 != nullptr);
        BOOST_CHECK_EQUAL(int{m3->slot}, expected["slot"].getInt<int>());
        BOOST_CHECK(m3->m6id.ToUint256() == HashFromHex(expected["m6id"].get_str()));
    } else if (type == "m4") {
        const auto* m4{std::get_if<M4AckBundles>(&*message)};
        BOOST_REQUIRE(m4 != nullptr);
        BOOST_CHECK_EQUAL(static_cast<int>(m4->version), expected["version"].getInt<int>());
        const UniValue& votes{expected["votes"]};
        BOOST_REQUIRE_EQUAL(m4->upvotes.size(), votes.size());
        for (size_t i{0}; i < votes.size(); ++i) {
            BOOST_CHECK_EQUAL(int{m4->upvotes[i]}, votes[i].getInt<int>());
        }
    } else if (type == "m7") {
        const auto* m7{std::get_if<M7BmmAccept>(&*message)};
        BOOST_REQUIRE(m7 != nullptr);
        BOOST_CHECK_EQUAL(int{m7->slot}, expected["slot"].getInt<int>());
        BOOST_CHECK(m7->sidechain_block_hash == HashFromHex(expected["hash"].get_str()));
    } else {
        BOOST_ERROR("unknown coinbase message type " + type);
    }
}

void CheckM8(const UniValue& vector)
{
    const auto request{ParseM8Request(ScriptFromVector(vector))};
    if (vector["result"].isNull()) {
        BOOST_CHECK(!request.has_value());
        return;
    }
    BOOST_REQUIRE(request.has_value());
    BOOST_CHECK_EQUAL(int{request->slot}, vector["result"]["slot"].getInt<int>());
    BOOST_CHECK(request->sidechain_block_hash == HashFromHex(vector["result"]["hash"].get_str()));
    BOOST_CHECK(request->prev_main_block_hash == HashFromHex(vector["result"]["prev"].get_str()));
}

void CheckM6id(const UniValue& vector)
{
    CMutableTransaction tx;
    BOOST_REQUIRE(DecodeHexTx(tx, vector["tx"].get_str()));
    const CAmount treasury_spent{vector["treasury_spent"].getInt<int64_t>()};

    M6Error error{};
    const auto blinded{BlindM6(CTransaction{tx}, treasury_spent, error)};
    if (vector["result"].isNull()) {
        BOOST_CHECK(!blinded.has_value());
        return;
    }
    BOOST_REQUIRE(blinded.has_value());
    BOOST_CHECK_EQUAL(int{blinded->slot}, vector["result"]["slot"].getInt<int>());
    BOOST_CHECK(blinded->m6id.ToUint256() == HashFromHex(vector["result"]["m6id"].get_str()));
}
} // namespace

BOOST_FIXTURE_TEST_SUITE(drivechain_vectors_tests, BasicTestingSetup)

BOOST_AUTO_TEST_CASE(agrees_with_the_reference_implementation)
{
    UniValue root;
    BOOST_REQUIRE(root.read(json_tests::drivechain_vectors));
    const UniValue& vectors{root["vectors"]};
    BOOST_REQUIRE(vectors.isArray());
    // A vector file that silently emptied would pass every check below.
    BOOST_REQUIRE(vectors.size() > 20);

    for (size_t i{0}; i < vectors.size(); ++i) {
        const UniValue& vector{vectors[i]};
        BOOST_TEST_CONTEXT(vector["name"].get_str())
        {
            const std::string kind{vector["kind"].get_str()};
            if (kind == "treasury") {
                CheckTreasury(vector);
            } else if (kind == "address") {
                CheckAddress(vector);
            } else if (kind == "coinbase") {
                CheckCoinbase(vector);
            } else if (kind == "m8") {
                CheckM8(vector);
            } else if (kind == "m6id") {
                CheckM6id(vector);
            } else {
                BOOST_ERROR("unknown vector kind " + kind);
            }
        }
    }
}

BOOST_AUTO_TEST_SUITE_END()
